version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:3000
    environment:
      - DATABASE_URL=postgresql://huyhiep4520:123456@postgresdb:5432/movie_db?schema=public
      - AWS_REGION=ap-southeast-1
      - AWS_ACCESS_KEY_ID=AKIA4AOBENU6BLVZKKG6
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_BUCKET_NAME='movie-416'

  postgresdb:
    image: postgres:14
    container_name: postgresdb
    restart: always
    environment:
      - POSTGRES_DB=movie_db
      - POSTGRES_USER=huyhiep4520
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '9003:80'

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local
