version: '3.8'
services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:phamhuyhiep4520@database-1.cacqs37jv4xx.ap-southeast-1.rds.amazonaws.com:5432/movie?schema=public
